site_name: 'Documentación de las prácticas'
site_description: 'Práctica: MkDocs'
site_author: 'Romel Oswaldo Caz Huisha'

theme:
  name: 'material'
  language: 'es'
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer 

nav:
  - Inicio: index.md
  - Prácticas:
      - Práctica 3.1: 3-1.md
      - Práctica 3.2: 3-2.md
      - Práctica 4.1: 4-1.md
      - Práctica 4.3: 4-3.md
      - Práctica 4.5: 4-5.md
      - Práctica 5.1: 5-1.md
      - Práctica 5.2: 5-2.md
      - Práctica 5.4: 5-4.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rcazhui1404/practica-iaw-6-1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/romel-oswaldo-caz-huisha-038b73304/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/romel_147/
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - attr_list

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

repo_url: https://github.com/rcazhui1404/practica-iaw-6-1
repo_name: 'GitHub'

copyright: 'Copyright © 2025 Romel'
